version: '3'
services:
  mongo:
    image: mongo:3.4
    volumes:
      - ./data:/data
    ports:
      - 27017:27017
  tomcat:
    image: tomcat:7.0
   environment:
      - TOMCAT_USERNAME=admin
      - TOMCAT_PASSWORD=password
    volumes:
      - ./war:/usr/local/tomcat/webapps
      - /usr/local/tomcat/conf/logging.properties:/log
    ports:
      - 8080:8080
    depends_on:
      - mongo



