version: '3'
services:
  mongodb:
    image: mongo:3.6.3
    ports:
      - 27017:27017
  tomcat:
    image: tomcat:9.0.22-jdk8-openjdk
    volumes:
      - ./war:/usr/local/tomcat/webapps
    ports:
      - 8080:8080
    depends_on:
      - mongodb



